### ISSUE TITLE
Task templates not creating tasks

### ISSUE THREAD

**Issue by nf0rc3r** [DRYTRIX/TimeTracker#368]
When I go to Project Templates and create a new template with 3 tasks in it, there are no tasks in the project, created from the template. When I try to edit the template, there are no tasks in it and no option to add tasks.

There is a message in the top right corner [object Object] and "Today you logged 0.0h across 0 projects. Great work!".

My expected behaviour is that tasks are created in the project when it is created in the template. Also the tasks should be editable in the already created template, in case they need to be changed.

Desktop, OS macOS Monterey, 12.7.6, Browser Chrome 143.0.7499.170

**Comment by evilguy4000** [comment]
✅ Issue Closed

Thanks for your report and contribution!
This issue has now been resolved or is no longer active.

If you’d like to support the project and future development, you can ☕ [buy me a coffee](https://buymeacoffee.com/drytrix)— it really helps keep things going.

Thanks again for helping improve this project! 🙌

**Comment by evilguy4000** [comment]
@nf0rc3r can you verify it is fixed?

**Comment by nf0rc3r** [comment]
Hello,

I tested again and the issue still remain, no tasks are created.

На ср, 31.12.2025 г. в 8:11 Dries Peeters ***@***.***> написа:

**Comment by evilguy4000** [comment]
@nf0rc3r can you check in v4.9.1

**Comment by nf0rc3r** [comment]
Hi,

I spent a lot of time today trying to upgrade from 4.8.0 to 4.9.1 and now
when 4.9.1, I am struggling to configure different currencies per client,
which I had in 4.8.0.

I will stop my testing at this stage and look for another solution. Thank
you for your help and your prompt responses.

На сб, 3.01.2026 г. в 21:30 Dries Peeters ***@***.***> написа:

**Comment by evilguy4000** [comment]
@nf0rc3r do you have any migration issues (which some people seem to be having?)

**Comment by nf0rc3r** [comment]
I had plenty of DB and Python issues.

На пн, 5.01.2026 г. в 18:46 Dries Peeters ***@***.***> написа:

**Comment by evilguy4000** [comment]
@nf0rc3r I have verified that it works in latest version.
