### ISSUE TITLE
Unable to deploy local-test docker; No database tables found

### ISSUE THREAD

**Issue by naerdinsul** [DRYTRIX/TimeTracker#373]
**Describe the bug**
Deploying the 'local-test' docker as per the directions on the website from a fresh VM does not work.  Build completes and then when 'timetracker-app-local-test' starts it fails to find any database tables and crashes out.

**To Reproduce**
1. From a fresh VM, follow the directions under "Getting Started" on the website

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 Proxmox Container

**Additional context**
See log file below

[timetracker-log.txt](https://github.com/user-attachments/files/24389062/timetracker-log.txt)

**Comment by evilguy4000** [comment]
@naerdinsul can you verify it is fixed?

**Comment by naerdinsul** [comment]
No, unfortunately it still does not work.  I've blown away everything and re-followed the "Getting Started" steps on the website.  Here is the new output:

```
timetracker-app-local-test  | [2025-12-31 13:35:17] Setting ownership to timetracker user...
timetracker-app-local-test  | [2025-12-31 13:35:17] Switching to timetracker user with gosu...
timetracker-app-local-test  | === TimeTracker Docker Container Starting ===
timetracker-app-local-test  | Timestamp: Wed Dec 31 13:35:17 CET 2025
timetracker-app-local-test  | Container ID: 958bf18373ed
timetracker-app-local-test  | Python version: Python 3.11.13
timetracker-app-local-test  | Flask version: Python 3.11.13
timetracker-app-local-test  | Flask 3.0.0
timetracker-app-local-test  | Werkzeug 3.0.6
timetracker-app-local-test  | Current directory: /app
timetracker-app-local-test  | User: timetracker
timetracker-app-local-test  | 
timetracker-app-local-test  | [2025-12-31 13:35:18] === TimeTracker Docker Entrypoint with Migration Detection ===
timetracker-app-local-test  | [2025-12-31 13:35:18] Database URL: sqlite:////data/timetracker.db
timetracker-app-local-test  | [2025-12-31 13:35:18] Ensuring /data directory exists and has proper permissions...
timetracker-app-local-test  | [2025-12-31 13:35:18] Setting permissions on /data directory...
timetracker-app-local-test  | [2025-12-31 13:35:18] Setting ownership of /data to current user (UID: 1000, GID: 1000)...
timetracker-app-local-test  | [2025-12-31 13:35:18] ✓ /data directory setup complete
timetracker-app-local-test  | [2025-12-31 13:35:18] Waiting for database to be available...
timetracker-app-local-test  | [2025-12-31 13:35:18] Database URL: sqlite:////data/timetracker.db
timetracker-app-local-test  | [2025-12-31 13:35:18] Attempt 1/60 to connect to database...
timetracker-app-local-test  | [2025-12-31 13:35:18] Testing SQLite connection...
timetracker-app-local-test  | [2025-12-31 13:35:18] ✓ SQLite database is available
timetracker-app-local-test  | [2025-12-31 13:35:18] Raw db_state output: 'fresh'
timetracker-app-local-test  | [2025-12-31 13:35:18] Detected database state: 'fresh'
timetracker-app-local-test  | [2025-12-31 13:35:18] Raw strategy output: 'fresh_init'
timetracker-app-local-test  | [2025-12-31 13:35:18] Selected migration strategy: 'fresh_init'
timetracker-app-local-test  | [2025-12-31 13:35:18] Fresh database detected - using standard initialization
timetracker-app-local-test  | [2025-12-31 13:35:18] Executing migration strategy: 'fresh_init'
timetracker-app-local-test  | [2025-12-31 13:35:18] Executing fresh_init strategy...
timetracker-app-local-test  | [2025-12-31 13:35:18] Executing fresh database initialization...
timetracker-app-local-test  | [2025-12-31 13:35:18] Checking for stale alembic_version table...
timetracker-app-local-test  | [2025-12-31 13:35:18] No core tables found, cleaning up stale alembic_version if present...
timetracker-app-local-test  | [2025-12-31 13:35:18] ⚠ Migrations directory already exists, checking if it's properly configured...
timetracker-app-local-test  | [2025-12-31 13:35:18] ✓ Migrations directory is properly configured, skipping init
timetracker-app-local-test  | [2025-12-31 13:35:18] Checking if we need to create initial migration...
timetracker-app-local-test  | [2025-12-31 13:35:18] ✓ Migration versions already exist
timetracker-app-local-test  | [2025-12-31 13:35:18] Checking current migration status...
timetracker-app-local-test  | [2025-12-31 13:35:25] Current migration revision: 
timetracker-app-local-test  | [2025-12-31 13:35:25] Applying pending migrations...
timetracker-app-local-test  | [2025-12-31 13:35:33] ✗ Migration application failed
timetracker-app-local-test  | [2025-12-31 13:35:33] Error details:
timetracker-app-local-test  | Could not query settings: (sqlite3.OperationalError) no such table: settings
timetracker-app-local-test  | [SQL: SELECT settings.id AS settings_id, settings.timezone AS settings_timezone, settings.currency AS settings_currency, settings.rounding_minutes AS settings_rounding_minutes, settings.single_active_timer AS settings_single_active_timer, settings.allow_self_register AS settings_allow_self_register, settings.idle_timeout_minutes AS settings_idle_timeout_minutes, settings.backup_retention_days AS settings_backup_retention_days, settings.backup_time AS settings_backup_time, settings.export_delimiter AS settings_export_delimiter, settings.company_name AS settings_company_name, settings.company_address AS settings_company_address, settings.company_email AS settings_company_email, settings.company_phone AS settings_company_phone, settings.company_website AS settings_company_website, settings.company_logo_filename AS settings_company_logo_filename, settings.company_tax_id AS settings_company_tax_id, settings.company_bank_info AS settings_company_bank_info, settings.invoice_pdf_template_html AS settings_invoice_pdf_template_html, settings.invoice_pdf_template_css AS settings_invoice_pdf_template_css, settings.invoice_pdf_design_json AS settings_invoice_pdf_design_json, settings.invoice_prefix AS settings_invoice_prefix, settings.invoice_start_number AS settings_invoice_start_number, settings.invoice_terms AS settings_invoice_terms, settings.invoice_notes AS settings_invoice_notes, settings.allow_analytics AS settings_allow_analytics, settings.kiosk_mode_enabled AS settings_kiosk_mode_enabled, settings.kiosk_auto_logout_minutes AS settings_kiosk_auto_logout_minutes, settings.kiosk_allow_camera_scanning AS settings_kiosk_allow_camera_scanning, settings.kiosk_require_reason_for_adjustments AS settings_kiosk_require_reason_for_adjustments, settings.kiosk_default_movement_type AS settings_kiosk_default_movement_type, settings.mail_enabled AS settings_mail_enabled, settings.mail_server AS settings_mail_server, settings.mail_port AS settings_mail_port, settings.mail_use_tls AS settings_mail_use_tls, settings.mail_use_ssl AS settings_mail_use_ssl, settings.mail_username AS settings_mail_username, settings.mail_password AS settings_mail_password, settings.mail_default_sender AS settings_mail_default_sender, settings.jira_client_id AS settings_jira_client_id, settings.jira_client_secret AS settings_jira_client_secret, settings.slack_client_id AS settings_slack_client_id, settings.slack_client_secret AS settings_slack_client_secret, settings.github_client_id AS settings_github_client_id, settings.github_client_secret AS settings_github_client_secret, settings.google_calendar_client_id AS settings_google_calendar_client_id, settings.google_calendar_client_secret AS settings_google_calendar_client_secret, settings.outlook_calendar_client_id AS settings_outlook_calendar_client_id, settings.outlook_calendar_client_secret AS settings_outlook_calendar_client_secret, settings.outlook_calendar_tenant_id AS settings_outlook_calendar_tenant_id, settings.microsoft_teams_client_id AS settings_microsoft_teams_client_id, settings.microsoft_teams_client_secret AS settings_microsoft_teams_client_secret, settings.microsoft_teams_tenant_id AS settings_microsoft_teams_tenant_id, settings.asana_client_id AS settings_asana_client_id, settings.asana_client_secret AS settings_asana_client_secret, settings.trello_api_key AS settings_trello_api_key, settings.trello_api_secret AS settings_trello_api_secret, settings.gitlab_client_id AS settings_gitlab_client_id, settings.gitlab_client_secret AS settings_gitlab_client_secret, settings.gitlab_instance_url AS settings_gitlab_instance_url, settings.quickbooks_client_id AS settings_quickbooks_client_id, settings.quickbooks_client_secret AS settings_quickbooks_client_secret, settings.xero_client_id AS settings_xero_client_id, settings.xero_client_secret AS settings_xero_client_secret, settings.created_at AS settings_created_at, settings.updated_at AS settings_updated_at 
timetracker-app-local-test  | FROM settings
timetracker-app-local-test  |  LIMIT ? OFFSET ?]
timetracker-app-local-test  | [parameters: (1, 0)]
timetracker-app-local-test  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
timetracker-app-local-test  | [2025-12-31 13:35:28,862] DEBUG in email: Could not load email settings from database: Working outside of application context.
timetracker-app-local-test  | 
timetracker-app-local-test  | This typically means that you attempted to use functionality that needed
timetracker-app-local-test  | the current application. To solve this, set up an application context
timetracker-app-local-test  | with app.app_context(). See the documentation for more information.
timetracker-app-local-test  | [2025-12-31 13:35:28,862] INFO in email: Using environment variable email configuration (database unavailable)
timetracker-app-local-test  | [2025-12-31 13:35:28,930] INFO in scheduled_tasks: Registered overdue invoices check task
timetracker-app-local-test  | [2025-12-31 13:35:28,930] INFO in scheduled_tasks: Registered weekly summaries task
timetracker-app-local-test  | [2025-12-31 13:35:28,931] INFO in scheduled_tasks: Registered budget alerts check task
timetracker-app-local-test  | [2025-12-31 13:35:28,931] INFO in scheduled_tasks: Registered recurring invoices generation task
timetracker-app-local-test  | [2025-12-31 13:35:28,931] INFO in scheduled_tasks: Registered monthly unpaid hours reports task
timetracker-app-local-test  | [2025-12-31 13:35:28,932] INFO in scheduled_tasks: Registered webhook retry task
timetracker-app-local-test  | [2025-12-31 13:35:28,932] INFO in scheduled_tasks: Registered expiring quotes check task
timetracker-app-local-test  | [2025-12-31 13:35:28,932] INFO in scheduled_tasks: Registered integration sync task
timetracker-app-local-test  | [2025-12-31 13:35:28,933] INFO in scheduled_tasks: Registered scheduled reports task
timetracker-app-local-test  | compiling catalog /app/translations/nb/LC_MESSAGES/messages.po to /app/translations/nb/LC_MESSAGES/messages.mo
timetracker-app-local-test  | compiling catalog /app/translations/it/LC_MESSAGES/messages.po to /app/translations/it/LC_MESSAGES/messages.mo
timetracker-app-local-test  | compiling catalog /app/translations/es/LC_MESSAGES/messages.po to /app/translations/es/LC_MESSAGES/messages.mo
timetracker-app-local-test  | compiling catalog /app/translations/nl/LC_MESSAGES/messages.po to /app/translations/nl/LC_MESSAGES/messages.mo
timetracker-app-local-test  | compiling catalog /app/translations/ar/LC_MESSAGES/messages.po to /app/translations/ar/LC_MESSAGES/messages.mo
timetracker-app-local-test  | compiling catalog /app/translations/en/LC_MESSAGES/messages.po to /app/translations/en/LC_MESSAGES/messages.mo
timetracker-app-local-test  | compiling catalog /app/translations/fi/LC_MESSAGES/messages.po to /app/translations/fi/LC_MESSAGES/messages.mo
timetracker-app-local-test  | compiling catalog /app/translations/de/LC_MESSAGES/messages.po to /app/translations/de/LC_MESSAGES/messages.mo
timetracker-app-local-test  | compiling catalog /app/translations/no/LC_MESSAGES/messages.po to /app/translations/no/LC_MESSAGES/messages.mo
timetracker-app-local-test  | compiling catalog /app/translations/fr/LC_MESSAGES/messages.po to /app/translations/fr/LC_MESSAGES/messages.mo
timetracker-app-local-test  | compiling catalog /app/translations/he/LC_MESSAGES/messages.po to /app/translations/he/LC_MESSAGES/messages.mo
timetracker-app-local-test  | [2025-12-31 13:35:31,208] INFO in __init__: Using database URL: sqlite:////data/timetracker.db
timetracker-app-local-test  | 2025-12-31 13:35:31,208 INFO: JSON logging initialized: /app/logs/app.jsonl [in /app/app/__init__.py:1392]
timetracker-app-local-test  | 2025-12-31 13:35:31,210 WARNING: Could not enable query logging: No such event 'before_cursor_execute' for target '<class 'sqlalchemy.orm.session.Session'>' [in /app/app/__init__.py:643]
timetracker-app-local-test  | 2025-12-31 13:35:31,210 INFO: TimeTracker build without analytics configuration [in /app/app/__init__.py:654]
timetracker-app-local-test  | 2025-12-31 13:35:32,289 INFO: Integration connectors registered [in /app/app/__init__.py:1059]
timetracker-app-local-test  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
timetracker-app-local-test  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
timetracker-app-local-test  | [2025-12-31 13:35:33] ✗ Migration strategy execution failed
timetracker-app-local-test exited with code 0
```
