### ISSUE TITLE
`csrf_token_missing_or_invalid`

### ISSUE THREAD

**Issue by nelsonni** [DRYTRIX/TimeTracker#77]
With [`v2.3.0`](https://github.com/DRYTRIX/TimeTracker/releases/tag/v2.3.0), there is a new error that has been introduced. If you navigate to an `Edit Task` screen, modify the task name, and attempt to click the `Update Task` button, the resulting error page appears (see screenshot) with the error:

```json
error	"csrf_token_missing_or_invalid"
```

<img width="695" height="356" alt="Image" src="https://github.com/user-attachments/assets/30839f2c-360d-434c-baba-80ea09d4c277" />

**Comment by clark-nnelson** [comment]
The issue actually extends further. Logging out of TimeTracker and then attempting to login results in the same CSRF token error from the login page:

<img width="1114" height="990" alt="Image" src="https://github.com/user-attachments/assets/a5143491-9e9d-45e7-a4bc-d7da50751e0a" />

**Comment by nelsonni** [comment]
Given that CSRF tokens are used to access a secure cookie for authorization purposes, I suspect it might be a transient issue associated with the OIDC updates (#71) and having previously set cookies prior to updating to [`v2.3.0`](https://github.com/DRYTRIX/TimeTracker/releases/tag/v2.3.0). I don't know how long these cookies typically take to expire, but the issue might be resolved by waiting until they do.

The only other thought I had was that I'm currently hosting TimeTracker internally and accessing it via HTTP as opposed to HTTPS. Does TimeTracker assume HTTPS connections now?

**Comment by Black-Lavender** [comment]
> Given that CSRF tokens are used to access a secure cookie for authorization purposes, I suspect it might be a transient issue associated with the OIDC updates ([#71](https://github.com/DRYTRIX/TimeTracker/issues/71)) and having previously set cookies prior to updating to [`v2.3.0`](https://github.com/DRYTRIX/TimeTracker/releases/tag/v2.3.0). I don't know how long these cookies typically take to expire, but the issue might be resolved by waiting until they do.
> 
> The only other thought I had was that I'm currently hosting TimeTracker internally and accessing it via HTTP as opposed to HTTPS. Does TimeTracker assume HTTPS connections now?

I had the same thought on waiting for them to expire, but I tried clearing cookies, private browser tabs, and multiple browsers that I have not access TimeTracker through. All of these resulted in the same error you mentioned, surely one of them would have worked right? I think you're right in your assessment on it being related to the OICD updates.

**Comment by evilguy4000** [comment]
I've looked into this issue, and created a fix, this was indeed an issue only related to csrf tokens.

**Comment by luarsh** [comment]
Hello,  
I recently discovered this project and installed TimeTracker in production mode. However, when I attempt to create my first user, I encounter the following error: {"error":"csrf_token_missing_or_invalid"}  

I found a suggested fix for this issue, but it does not seem to work with the latest version.

**Comment by nelsonni** [comment]
> I've looked into this issue, and created a fix, this was indeed an issue only related to csrf tokens.

I just updated to [`v2.3.1`](https://github.com/DRYTRIX/TimeTracker/releases/tag/v2.3.1) to check, and the issue still persists. Same behavior on several different POST requests.

**Comment by nelsonni** [comment]
I'm including the Browser Console logs from my attemtps to login, which result in the `csrf_token_missing_or_invalid` error page: [console-export-2025-10-11_10-30-46.log](https://github.com/user-attachments/files/22865763/console-export-2025-10-11_10-30-46.log).

Additionally, the relevant login requests from the `TimeTracker` Docker logs show:
```Containerfile
timetracker-app-remote  | 2025-10-11 10:32:28,042 INFO: GET /login from 10.0.0.2 UA=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0 [in /app/app/__init__.py:201]
timetracker-app-remote  | 2025-10-11 10:32:28,042 INFO: GET /login from 10.0.0.2 [in /app/app/routes/auth.py:19]
timetracker-app-remote  | 10.0.0.2 - - [11/Oct/2025:10:32:28 -0700] "GET /login?next=%2F HTTP/1.1" 200 26794 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app-remote  | 10.0.0.2 - - [11/Oct/2025:10:32:28 -0700] "GET /static/toast-notifications.css?v=v2.3.1 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app-remote  | 10.0.0.2 - - [11/Oct/2025:10:32:28 -0700] "GET /static/images/drytrix-logo.svg HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app-remote  | 10.0.0.2 - - [11/Oct/2025:10:32:28 -0700] "GET /static/toast-notifications.js?v=v2.3.1 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app-remote  | 2025-10-11 10:32:31,402 INFO: The CSRF session token is missing. [in /usr/local/lib/python3.11/site-packages/flask_wtf/csrf.py:263]
timetracker-app-remote  | 2025-10-11 10:32:31,402 INFO: POST /login -> 400 from 10.0.0.2 [in /app/app/__init__.py:216]
timetracker-app-remote  | 10.0.0.2 - - [11/Oct/2025:10:32:31 -0700] "POST /login HTTP/1.1" 400 42 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
```

I believe the errors in the Browser Console that matter for this issue relate to `SessionStore.sys.mjs` and `LinkHandlerParent.sys.mjs`:

```javascript
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsISpeculativeConnect.speculativeConnect]
    prepareConnectionToHost resource:///modules/sessionstore/SessionStore.sys.mjs:5936
    speculativeConnectOnTabHover resource:///modules/sessionstore/SessionStore.sys.mjs:5959
    speculativeConnectOnTabHover resource:///modules/sessionstore/SessionStore.sys.mjs:666
    _mouseenter chrome://browser/content/tabbrowser/tab.js:633
    on_mouseover chrome://browser/content/tabbrowser/tab.js:419
    handleEvent chrome://global/content/customElements.js:459
[SessionStore.sys.mjs:5940:17](resource:///modules/sessionstore/SessionStore.sys.mjs)
```
```javascript
NS_ERROR_FILE_TOO_BIG: Component returned failure code: 0x8052000f (NS_ERROR_FILE_TOO_BIG) [nsIFaviconService.setFaviconForPage]
    setIconFromLink resource:///actors/LinkHandlerParent.sys.mjs:142
    receiveMessage resource:///actors/LinkHandlerParent.sys.mjs:55
[LinkHandlerParent.sys.mjs:151:17](resource:///actors/LinkHandlerParent.sys.mjs)
```

**Comment by evilguy4000** [comment]
@luarsh, what version have you installed? 
I'm currently looking into fixing this issue, but i've not been able to reproduce on my system.

@nelsonni i've updated the version to a new release, please make sure the .env file contains these.
```
 # TROUBLESHOOTING: If forms fail with "CSRF token missing or invalid":
      # 1. Verify SECRET_KEY is set and doesn't change between restarts
      # 2. Check CSRF is enabled: WTF_CSRF_ENABLED=true
      # 3. Ensure cookies are enabled in your browser
      # 4. If behind a reverse proxy, ensure it forwards cookies correctly
      # 5. Check the token hasn't expired (increase WTF_CSRF_TIME_LIMIT if needed)
      # 6. Verify all app replicas use the SAME SECRET_KEY
      # For details: docs/CSRF_CONFIGURATION.md
```

**Comment by evilguy4000** [comment]
@clark-nnelson @nelsonni , i've updated the dockerfile from the release to contain these settings.

**Comment by nelsonni** [comment]
I updated to [`v2.3.2`](https://github.com/DRYTRIX/TimeTracker/releases/tag/v2.3.2) and then [`v2.3.3`](https://github.com/DRYTRIX/TimeTracker/releases/tag/v2.3.3). After verifying all of those troubleshooting steps, I noticed that I had `WTF_CSRF_ENABLED=false` from a previous version (so I updated that environment variable as well). I no longer get `csrf_token_missing_or_invalid` errors, but instead the login page silently fails, and I see the following in the Docker logs:

```Dockerfile
timetracker-app-remote  | 2025-10-11 12:39:31,418 INFO: The CSRF session token is missing. [in /usr/local/lib/python3.11/site-packages/flask_wtf/csrf.py:263]
timetracker-app-remote  | 2025-10-11 12:39:31,418 INFO: POST /login -> 302 from 10.0.0.2 [in /app/app/__init__.py:217]
```

I tried clearing cookies and site data several times to see if a new CSRF session token will be issued, but that didn't work. For the purposes of recreating the issue, I'm running Firefox 143.0.4 (aarch64) on MacOS 10.15.

**Comment by nelsonni** [comment]
Looking through the [`docs/CSRF_CONFIGURATION.md`](https://github.com/DRYTRIX/TimeTracker/blob/main/docs/CSRF_CONFIGURATION.md) file, I noticed a callout to verify that a hidden field `<input type="hidden" name="csrf_token" value="...">` should exist in the DOM of a form page. I can verify that I am indeed seeing that field from the login page:
```html
<input type="hidden" name="csrf_token" value="IjBhMTk4NjMzMTAwMzU2OTdkZjRkNDc4YTA2M2YzYjcwOWY0N2E3ZTgi.aOq1Lg.ZJv-KUu-HnKjuDu-I89roTdQaeY">
```

(Note: I'm not obfuscating the true CSRF token in my example, since I'm also updating my `SECRET_KEY` and letting it hash a new CSRF token and that token means nothing outside my local network. But to anyone else trying to follow along, BEWARE of exposing your secrets.)

**Comment by nelsonni** [comment]
According to a bit of AI-based debugging (so grain of salt required), and based on messages I'm seeing in my Docker logs, the issue is:

> The error `The CSRF session token is missing` means that Flask-WTF is looking for a `csrf_token` key in the session object, but it's not there. This is different from the CSRF token being missing from the form - the issue is that the server-side session doesn't have the token stored.
>
> When you see a 302 redirect instead of a proper error, it typically means the login is "failing" but redirecting you back to the login page without showing an error message.

The AI also provided some troubleshooting steps, which included verifying that a `session` cookie is getting set. I checked in `Developer Tools`→`Storage`→`Cookies` (specific to Firefox) for my local instance of TimeTracker, and it is listed, but shows `No data for selected host`.

The other suggestion it made was more focused on the code and configuration:

> Most Likely Fix
> Given that you're in a Docker environment and getting this specific error, I'd bet on multiple Gunicorn workers being the issue. Start by setting `--workers 1` and see if that resolves it immediately.

Hopefully this helps @evilguy4000. Love the app and the work!

**Comment by evilguy4000** [comment]
@nelsonni I have implemented a "fix" which is more an enforcement of requirements for the csrf feature. please test and validate, if there are still issues, we can reopen the issue.

**Comment by nelsonni** [comment]
Still an issue on [`v2.3.4`](https://github.com/DRYTRIX/TimeTracker/releases/tag/v2.3.4), I see the following in my Docker logs (after a fresh install and a second run, hence the existing PostgresSQL database):

```javascript
timetracker-db  | 
timetracker-db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
timetracker-db  | 
timetracker-db  | 2025-10-12 19:38:13.568 PDT [1] LOG:  starting PostgreSQL 16.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
timetracker-db  | 2025-10-12 19:38:13.568 PDT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
timetracker-db  | 2025-10-12 19:38:13.568 PDT [1] LOG:  listening on IPv6 address "::", port 5432
timetracker-db  | 2025-10-12 19:38:13.586 PDT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
timetracker-db  | 2025-10-12 19:38:13.606 PDT [29] LOG:  database system was shut down at 2025-10-12 19:36:09 PDT
timetracker-db  | 2025-10-12 19:38:13.620 PDT [1] LOG:  database system is ready to accept connections
timetracker-app  | ✓ Table projects exists with correct schema
timetracker-app  | ✓ Table tasks exists with correct schema
timetracker-app  | ✓ Table time_entries exists with correct schema
timetracker-app  | ✓ Table settings exists with correct schema
timetracker-app  | ✓ Table invoices exists with correct schema
timetracker-app  | ✓ Table invoice_items exists with correct schema
timetracker-app  | 
timetracker-app  | --- Creating indexes ---
timetracker-app  | ✓ Indexes created for clients
timetracker-app  | ✓ Indexes created for users
timetracker-app  | ✓ Indexes created for projects
timetracker-app  | ✓ Indexes created for tasks
timetracker-app  | ✓ Indexes created for time_entries
timetracker-app  | ✓ Indexes created for invoices
timetracker-app  | ✓ Indexes created for invoice_items
timetracker-app  | 
timetracker-app  | --- Creating triggers ---
timetracker-app  | Creating triggers...
timetracker-app  | ✓ Triggers created successfully
timetracker-app  | 
timetracker-app  | --- Running legacy migrations ---
timetracker-app  | 
timetracker-app  | --- Inserting initial data ---
timetracker-app  | Inserting initial data...
timetracker-app  | ✓ Initial data inserted successfully
timetracker-app  | 
timetracker-app  | --- Verifying database schema ---
timetracker-app  | Verifying database schema...
timetracker-app  | ✓ Database schema verification passed
timetracker-app  | 
timetracker-app  | ✓ Enhanced database initialization completed successfully
timetracker-app  | 
timetracker-app  | ✓ Database initialization and migration completed successfully
timetracker-app  | Ensuring default settings and admin user exist (flask init_db)...
timetracker-app  | Warning: flask init_db failed (continuing): exit 2
timetracker-app  | stdout: Warning: Could not create log file '/app/logs/timetracker.log': [Errno 13] Permission denied: '/app/logs/timetracker.log'
timetracker-app  | Logging to console only
timetracker-app  | stderr: compiling catalog /app/translations/de/LC_MESSAGES/messages.po to /app/translations/de/LC_MESSAGES/messages.mo
timetracker-app  | compiling catalog /app/translations/fi/LC_MESSAGES/messages.po to /app/translations/fi/LC_MESSAGES/messages.mo
timetracker-app  | compiling catalog /app/translations/it/LC_MESSAGES/messages.po to /app/translations/it/LC_MESSAGES/messages.mo
timetracker-app  | compiling catalog /app/translations/fr/LC_MESSAGES/messages.po to /app/translations/fr/LC_MESSAGES/messages.mo
timetracker-app  | compiling catalog /app/translations/en/LC_MESSAGES/messages.po to /app/translations/en/LC_MESSAGES/messages.mo
timetracker-app  | compiling catalog /app/translations/nl/LC_MESSAGES/messages.po to /app/translations/nl/LC_MESSAGES/messages.mo
timetracker-app  | 2025-10-12 19:38:28,626 INFO: OIDC client registered with issuer https://auth.casapdx.top/application/o/time-tracker/ [in /app/app/__init__.py:439]
timetracker-app  | Usage: flask [OPTIONS] COMMAND [ARGS]...
timetracker-app  | Try 'flask --help' for help.
timetracker-app  | 
timetracker-app  | Error: No such command 'init_db'.
timetracker-app  | Starting application...
timetracker-app  | [2025-10-12 19:38:29 -0700] [1] [INFO] Starting gunicorn 23.0.0
timetracker-app  | [2025-10-12 19:38:29 -0700] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
timetracker-app  | [2025-10-12 19:38:29 -0700] [1] [INFO] Using worker: eventlet
timetracker-app  | [2025-10-12 19:38:29 -0700] [78] [INFO] Booting worker with pid: 78
timetracker-app  | compiling catalog /app/translations/de/LC_MESSAGES/messages.po to /app/translations/de/LC_MESSAGES/messages.mo
timetracker-app  | compiling catalog /app/translations/fi/LC_MESSAGES/messages.po to /app/translations/fi/LC_MESSAGES/messages.mo
timetracker-app  | compiling catalog /app/translations/it/LC_MESSAGES/messages.po to /app/translations/it/LC_MESSAGES/messages.mo
timetracker-app  | compiling catalog /app/translations/fr/LC_MESSAGES/messages.po to /app/translations/fr/LC_MESSAGES/messages.mo
timetracker-app  | compiling catalog /app/translations/en/LC_MESSAGES/messages.po to /app/translations/en/LC_MESSAGES/messages.mo
timetracker-app  | compiling catalog /app/translations/nl/LC_MESSAGES/messages.po to /app/translations/nl/LC_MESSAGES/messages.mo
timetracker-app  | Warning: Could not create log file '/app/logs/timetracker.log': [Errno 13] Permission denied: '/app/logs/timetracker.log'
timetracker-app  | Logging to console only
timetracker-app  | 2025-10-12 19:38:30,397 INFO: OIDC client registered with issuer https://auth.casapdx.top/application/o/time-tracker/ [in /app/app/__init__.py:439]
timetracker-app  | 127.0.0.1 - - [12/Oct/2025:19:38:30 -0700] "GET /_health HTTP/1.1" 200 21 "-" "curl/7.74.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:42 -0700] "GET / HTTP/1.1" 302 217 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 2025-10-12 19:38:42,912 INFO: GET /login from 10.0.0.2 UA=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0 [in /app/app/__init__.py:203]
timetracker-app  | 2025-10-12 19:38:42,912 INFO: GET /login from 10.0.0.2 [in /app/app/routes/auth.py:19]
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:43 -0700] "GET /login?next=%2F HTTP/1.1" 200 27093 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:43 -0700] "GET /static/toast-notifications.css?v=dev-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:43 -0700] "GET /static/toast-notifications.js?v=dev-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:43 -0700] "GET /static/images/drytrix-logo.svg HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 2025-10-12 19:38:55,587 INFO: The CSRF session token is missing. [in /usr/local/lib/python3.11/site-packages/flask_wtf/csrf.py:263]
timetracker-app  | 2025-10-12 19:38:55,587 WARNING: CSRF failure: path=/login method=POST form=True json=False ref=None user=None reason=The CSRF session token is missing. [in /app/app/__init__.py:294]
timetracker-app  | 2025-10-12 19:38:55,587 INFO: POST /login -> 302 from 10.0.0.2 [in /app/app/__init__.py:218]
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:55 -0700] "POST /login HTTP/1.1" 302 207 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:55 -0700] "GET /dashboard HTTP/1.1" 302 235 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 2025-10-12 19:38:55,660 INFO: GET /login from 10.0.0.2 UA=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0 [in /app/app/__init__.py:203]
timetracker-app  | 2025-10-12 19:38:55,660 INFO: GET /login from 10.0.0.2 [in /app/app/routes/auth.py:19]
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:55 -0700] "GET /login?next=%2Fdashboard HTTP/1.1" 200 27156 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:55 -0700] "GET /static/toast-notifications.css?v=dev-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:55 -0700] "GET /static/toast-notifications.js?v=dev-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:55 -0700] "GET /static/images/drytrix-logo.svg HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 2025-10-12 19:38:57,910 INFO: The CSRF session token is missing. [in /usr/local/lib/python3.11/site-packages/flask_wtf/csrf.py:263]
timetracker-app  | 2025-10-12 19:38:57,910 WARNING: CSRF failure: path=/login method=POST form=True json=False ref=None user=None reason=The CSRF session token is missing. [in /app/app/__init__.py:294]
timetracker-app  | 2025-10-12 19:38:57,911 INFO: POST /login -> 302 from 10.0.0.2 [in /app/app/__init__.py:218]
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:57 -0700] "POST /login HTTP/1.1" 302 207 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:57 -0700] "GET /dashboard HTTP/1.1" 302 235 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 2025-10-12 19:38:57,965 INFO: GET /login from 10.0.0.2 UA=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0 [in /app/app/__init__.py:203]
timetracker-app  | 2025-10-12 19:38:57,966 INFO: GET /login from 10.0.0.2 [in /app/app/routes/auth.py:19]
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:57 -0700] "GET /login?next=%2Fdashboard HTTP/1.1" 200 27156 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:58 -0700] "GET /static/toast-notifications.css?v=dev-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:58 -0700] "GET /static/toast-notifications.js?v=dev-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:38:58 -0700] "GET /static/images/drytrix-logo.svg HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 127.0.0.1 - - [12/Oct/2025:19:39:00 -0700] "GET /_health HTTP/1.1" 200 21 "-" "curl/7.74.0"
timetracker-app  | 127.0.0.1 - - [12/Oct/2025:19:39:30 -0700] "GET /_health HTTP/1.1" 200 21 "-" "curl/7.74.0"
timetracker-app  | 2025-10-12 19:39:51,355 INFO: GET /login from 10.0.0.2 UA=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0 [in /app/app/__init__.py:203]
timetracker-app  | 2025-10-12 19:39:51,356 INFO: GET /login from 10.0.0.2 [in /app/app/routes/auth.py:19]
timetracker-app  | 10.0.0.2 - - [12/Oct/2025:19:39:51 -0700] "GET /login?next=%2Fdashboard HTTP/1.1" 200 27156 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0"
timetracker-app  | 127.0.0.1 - - [12/Oct/2025:19:40:00 -0700] "GET /_health HTTP/1.1" 200 21 "-" "curl/7.74.0"
timetracker-app  | 127.0.0.1 - - [12/Oct/2025:19:40:30 -0700] "GET /_health HTTP/1.1" 200 21 "-" "curl/7.74.0"
timetracker-app  | 127.0.0.1 - - [12/Oct/2025:19:41:00 -0700] "GET /_health HTTP/1.1" 200 21 "-" "curl/7.74.0"

```

**Comment by evilguy4000** [comment]
Hi @nelsonni,
Can you provide me with a more detailed setup you have. Will try to reproduce with your settings.

**Comment by evilguy4000** [comment]
@nelsonni can you also post your .env & your docker-compose.yml file?
Are you running in https mode or not?

**Comment by luarsh** [comment]
Hello,

I take time to reproduce and try to solve the problem. I use now the latest version v2.3.4 and it's different. Now, when I log in for the first time and enter my username, the login page keeps reloading in a loop.. The docker logs are :
```
INFO: The CSRF session token is missing. [in /usr/local/lib/python3.11/site-packages/flask_wtf/csrf.py:263]
2025-10-13 09:41:12,380 WARNING: CSRF failure: path=/login method=POST form=True json=False ref=None user=None reason=The CSRF session token is missing. [in /app/app/__init__.py:294]
2025-10-13 09:41:12,380 INFO: POST /login -> 302 from 192.168.0.15 [in /app/app/__init__.py:218] 
```
I use docker-compose in production mode and specify a key (generation with python command). I verify all troubleshooting, normally it's okey. The source code contain csrf-token

**Comment by evilguy4000** [comment]
@luarsh, can you check in your browser if you have cookies related to the application:
kr 
Dries

**Comment by evilguy4000** [comment]
@luarsh @nelsonni i have released a more hardened version for the csrf and i make sure that it persists in cookies/memory.
docker pull ghcr.io/drytrix/timetracker:2.3.5

**Comment by luarsh** [comment]
Now I test v2.3.5 but if I go to the developper tools, I don't have any cookie^^

**Comment by evilguy4000** [comment]
So you don't have any cookies right now? do you connect via localhost or is it running on another machine?

**Comment by evilguy4000** [comment]
I have currently been able to reproduce.
I've been testing using localhost & not remote connection, if i use the remote connection I do see that the cookie does not get added. 
Will work on a fix now.

**Comment by luarsh** [comment]
Okey good news, thank you so much ! :)

**Comment by evilguy4000** [comment]
@luarsh a fix is available

**Comment by luarsh** [comment]
Thank you so much for your time, this fix is OK ! :)

**Comment by evilguy4000** [comment]
✅ Issue Closed

Thanks for your report and contribution!
This issue has now been resolved or is no longer active.

If you’d like to support the project and future development, you can ☕ [buy me a coffee](https://buymeacoffee.com/drytrix)— it really helps keep things going.

Thanks again for helping improve this project! 🙌
